@MCWorkshop.Server_HostAddress = http://localhost:5294

GET {{MCWorkshop.Server_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{MCWorkshop.Server_HostAddress}}/api/booking/availability
Accept: application/json

###
GET {{MCWorkshop.Server_HostAddress}}/api/storage/space
Accept: application/json

###
POST {{MCWorkshop.Server_HostAddress}}/api/storage
Accept: application/json
Content-Type: application/json

###
GET {{MCWorkshop.Server_HostAddress}}/api/inventory
Accept: application/json

###
GET {{MCWorkshop.Server_HostAddress}}/api/bike
Accept: application/json